[package]
name = "sudoku_native"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
rfd = "0.15.4"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = {version = "1.48.0", features = ["full"]}
